"""empty message

Revision ID: d7e851cd7ff2
Revises: a9cfde3741a6
Create Date: 2022-05-17 19:55:58.190479

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd7e851cd7ff2'
down_revision = 'a9cfde3741a6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('student', sa.Column('dob', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('student', 'dob')
    # ### end Alembic commands ###
